name: Sync to DECA fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to stp-deca fork
        env:
          DECA_TOKEN: ${{ secrets.DECA_SYNC_TOKEN }}
        run: |
          git remote add deca https://github.com/stp-deca/stpdecawebsite.git
          git config --global credential.helper store
          echo "https://Ishan-Singhal:${DECA_TOKEN}@github.com" > ~/.git-credentials
          git push deca main --force