name: Sync to DECA fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check token exists
        run: |
          if [ -z "${{ secrets.DECA_SYNC_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
          else
            echo "TOKEN EXISTS"
          fi
      - name: Push to stp-deca fork
        run: |
          git remote add deca https://Ishan-Singhal:${{ secrets.DECA_SYNC_TOKEN }}@github.com/stp-deca/stpdecawebsite.git
          git push deca main --force